var PRODUCTS = [
  {
    "name": "Premium Kids' Casual Shoes",
    "image": "img/儿童鞋1.jpg",
    "category": "kids-shoes",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "22-35",
    "colors": "6 Colors",
    "season": "All Season",
    "desc": "High-quality casual shoes for kids with durable rubber soles and comfortable inner lining. Perfect for everyday wear and outdoor activities.",
    "moq": "300 pcs"
  },
  {
    "name": "Fashion Kids' Sneakers",
    "image": "img/儿童鞋2.jpg",
    "category": "kids-shoes",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "24-38",
    "colors": "5 Colors",
    "season": "All Season",
    "desc": "Stylish sneakers with breathable mesh upper and anti-slip sole. Lightweight and comfortable for active kids.",
    "moq": "250 pcs"
  },
  {
    "name": "Boys' Sports Running Shoes",
    "image": "img/儿童鞋3.jpg",
    "category": "kids-shoes",
    "tag": "Kids'",
    "stockBadge": "Limited",
    "sizes": "26-40",
    "colors": "4 Colors",
    "season": "All Season",
    "desc": "Professional sports shoes with cushioning insole and shock-absorbing technology. Ideal for running and sports activities.",
    "moq": "200 pcs"
  },
  {
    "name": "Cute Baby Romper Set",
    "image": "img/婴儿套装1.jpg",
    "category": "baby-rompers",
    "tag": "Baby",
    "stockBadge": "In Stock",
    "sizes": "3M-24M",
    "colors": "8 Colors",
    "season": "All Season",
    "desc": "Soft cotton romper sets for babies with adorable patterns. Includes matching hat and booties. Gentle on baby's skin.",
    "moq": "500 pcs"
  },
  {
    "name": "Newborn Bodysuit Pack",
    "image": "img/婴儿套装2.jpg",
    "category": "baby-rompers",
    "tag": "Baby",
    "stockBadge": "In Stock",
    "sizes": "0M-18M",
    "colors": "10 Colors",
    "season": "All Season",
    "desc": "Pack of newborn bodysuits made from premium organic cotton. Snap closures for easy diaper changes.",
    "moq": "600 pcs"
  },
  {
    "name": "Baby Onesie Collection",
    "image": "img/婴儿套装3.jpg",
    "category": "baby-rompers",
    "tag": "Baby",
    "stockBadge": "Limited",
    "sizes": "3M-24M",
    "colors": "6 Colors",
    "season": "All Season",
    "desc": "Cute printed onesies with envelope neck design. Soft, stretchable fabric for maximum comfort.",
    "moq": "400 pcs"
  },
  {
    "name": "Girls' Princess Party Dress",
    "image": "img/儿童公主裙1.jpg",
    "category": "girls-princess",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "3-12Y",
    "colors": "4 Colors",
    "season": "Spring/Summer",
    "desc": "Elegant princess dress with tulle skirt and lace details. Perfect for birthdays, parties, and special occasions.",
    "moq": "200 pcs"
  },
  {
    "name": "Royal Ball Gown Dress",
    "image": "img/儿童公主裙2.jpg",
    "category": "girls-princess",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "4-14Y",
    "colors": "3 Colors",
    "season": "Spring/Summer",
    "desc": "Luxurious ball gown with layered skirt and sparkling embellishments. Fit for a little princess.",
    "moq": "150 pcs"
  },
  {
    "name": "Flower Girl Princess Dress",
    "image": "img/儿童公主裙3.jpg",
    "category": "girls-princess",
    "tag": "Girls'",
    "stockBadge": "Limited",
    "sizes": "3-10Y",
    "colors": "5 Colors",
    "season": "Spring/Summer",
    "desc": "Beautiful flower girl dress with floral embroidery and satin ribbon. Ideal for weddings and formal events.",
    "moq": "180 pcs"
  },
  {
    "name": "Kids' Floral Print Dress",
    "image": "img/儿童花布连衣裙1.jpg",
    "category": "girls-printed",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "3-12Y",
    "colors": "6 Colors",
    "season": "Summer",
    "desc": "Pretty floral print dress with comfortable cotton fabric. Breathable and stylish for summer days.",
    "moq": "250 pcs"
  },
  {
    "name": "Girls' Hawaiian Dress",
    "image": "img/儿童花布连衣裙2.jpg",
    "category": "girls-printed",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "4-14Y",
    "colors": "5 Colors",
    "season": "Summer",
    "desc": "Hawaiian style floral dress with ruffled sleeves and hem. Vibrant prints perfect for vacation.",
    "moq": "200 pcs"
  },
  {
    "name": "Cotton Floral Sundress",
    "image": "img/儿童花布连衣裙3.jpg",
    "category": "girls-printed",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "3-10Y",
    "colors": "7 Colors",
    "season": "Summer",
    "desc": "Lightweight cotton sundress with beautiful floral patterns. Comfortable and easy to care for.",
    "moq": "300 pcs"
  },
  {
    "name": "Boys' 2-Piece Casual Set",
    "image": "img/儿童套装1.jpg",
    "category": "boys-sets",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "3-12Y",
    "colors": "5 Colors",
    "season": "All Season",
    "desc": "Comfortable 2-piece set including t-shirt and pants. Made from soft cotton for everyday wear.",
    "moq": "300 pcs"
  },
  {
    "name": "Kids' Tracksuit Set",
    "image": "img/儿童套装2.jpg",
    "category": "boys-sets",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "4-14Y",
    "colors": "4 Colors",
    "season": "All Season",
    "desc": "Sporty tracksuit set with zip-up jacket and matching pants. Great for school and outdoor activities.",
    "moq": "250 pcs"
  },
  {
    "name": "Children's Playwear Set",
    "image": "img/儿童套装3.jpg",
    "category": "boys-sets",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "3-10Y",
    "colors": "6 Colors",
    "season": "All Season",
    "desc": "Durable playwear set designed for active kids. Stain-resistant fabric and reinforced seams.",
    "moq": "280 pcs"
  },
  {
    "name": "Boys' Fashion 2-Piece Set",
    "image": "img/男童套装1.jpg",
    "category": "boys-sets",
    "tag": "Boys'",
    "stockBadge": "In Stock",
    "sizes": "4-12Y",
    "colors": "4 Colors",
    "season": "Spring/Fall",
    "desc": "Stylish boys' outfit with button-down shirt and shorts/pants. Perfect for casual occasions.",
    "moq": "200 pcs"
  },
  {
    "name": "Little Boys' Smart Set",
    "image": "img/男童套装2.jpg",
    "category": "boys-sets",
    "tag": "Boys'",
    "stockBadge": "In Stock",
    "sizes": "3-10Y",
    "colors": "5 Colors",
    "season": "Spring/Fall",
    "desc": "Fashionable boys' two-piece set with modern design. High-quality fabric for comfort and style.",
    "moq": "220 pcs"
  },
  {
    "name": "Boys' Casual Outfit",
    "image": "img/男童套装3.jpg",
    "category": "boys-sets",
    "tag": "Boys'",
    "stockBadge": "Limited",
    "sizes": "5-14Y",
    "colors": "3 Colors",
    "season": "Spring/Fall",
    "desc": "Trendy boys' casual set with hoodie and jeans. Comfortable yet stylish for everyday wear.",
    "moq": "180 pcs"
  },
  {
    "name": "Women's Elegant Maxi Dress",
    "image": "img/成人连衣裙1.jpg",
    "category": "womens-dresses",
    "tag": "Women's",
    "stockBadge": "In Stock",
    "sizes": "S-XXL",
    "colors": "4 Colors",
    "season": "Spring/Summer",
    "desc": "Elegant maxi dress with flowing fabric and flattering silhouette. Perfect for formal events and special occasions.",
    "moq": "150 pcs"
  },
  {
    "name": "Fashion Women's Midi Dress",
    "image": "img/成人连衣裙2.jpg",
    "category": "womens-dresses",
    "tag": "Women's",
    "stockBadge": "In Stock",
    "sizes": "S-XXL",
    "colors": "6 Colors",
    "season": "Spring/Summer",
    "desc": "Stylish midi dress with modern design and comfortable fit. Versatile for work or casual outings.",
    "moq": "180 pcs"
  },
  {
    "name": "Ladies' Summer Dress",
    "image": "img/成人连衣裙3.jpg",
    "category": "womens-dresses",
    "tag": "Women's",
    "stockBadge": "Limited",
    "sizes": "S-XXL",
    "colors": "5 Colors",
    "season": "Summer",
    "desc": "Lightweight summer dress with beautiful prints. Breathable fabric for hot weather comfort.",
    "moq": "120 pcs"
  },
  {
    "name": "Boys' Formal Suit Set",
    "image": "img/男童西装1.jpg",
    "category": "boys-formal",
    "tag": "Boys'",
    "stockBadge": "In Stock",
    "sizes": "4-14Y",
    "colors": "3 Colors",
    "season": "All Season",
    "desc": "Handsome formal suit for boys with jacket, vest, pants, and tie. Perfect for weddings and special events.",
    "moq": "100 pcs"
  },
  {
    "name": "Kids' Tuxedo Set",
    "image": "img/男童西装2.jpg",
    "category": "boys-formal",
    "tag": "Boys'",
    "stockBadge": "In Stock",
    "sizes": "5-12Y",
    "colors": "2 Colors",
    "season": "All Season",
    "desc": "Classic tuxedo set with black jacket, white shirt, and bow tie. Formal wear for special occasions.",
    "moq": "80 pcs"
  },
  {
    "name": "Smart Boys' Blazer Set",
    "image": "img/男童西装3.jpg",
    "category": "boys-formal",
    "tag": "Boys'",
    "stockBadge": "Limited",
    "sizes": "4-10Y",
    "colors": "4 Colors",
    "season": "All Season",
    "desc": "Stylish blazer set with tailored fit. Includes blazer and matching pants for a complete look.",
    "moq": "90 pcs"
  },
  {
    "name": "Classic School Backpack",
    "image": "img/书包1.jpg",
    "category": "school-bags",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "6 Colors",
    "season": "All Season",
    "desc": "Durable school backpack with multiple compartments and padded shoulder straps. Ergonomic design for comfortable carrying.",
    "moq": "300 pcs"
  },
  {
    "name": "Student Book Bag",
    "image": "img/书包2.jpg",
    "category": "school-bags",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "5 Colors",
    "season": "All Season",
    "desc": "Stylish student book bag with reflective strips for safety. Large capacity for textbooks and supplies.",
    "moq": "250 pcs"
  },
  {
    "name": "Elementary School Bag",
    "image": "img/书包3.jpg",
    "category": "school-bags",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "4 Colors",
    "season": "All Season",
    "desc": "Cute cartoon-themed school bag with lightweight design. Perfect for elementary school students.",
    "moq": "280 pcs"
  },
  {
    "name": "Trendy Casual Backpack",
    "image": "img/潮流背包1.jpg",
    "category": "stylish-backpacks",
    "tag": "Unisex",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "5 Colors",
    "season": "All Season",
    "desc": "Fashionable everyday backpack with modern design. Durable material and comfortable straps for daily use.",
    "moq": "200 pcs"
  },
  {
    "name": "Fashion Travel Backpack",
    "image": "img/潮流背包2.jpg",
    "category": "stylish-backpacks",
    "tag": "Unisex",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "4 Colors",
    "season": "All Season",
    "desc": "Spacious travel backpack with multiple pockets and laptop compartment. Ideal for trips and commuting.",
    "moq": "180 pcs"
  },
  {
    "name": "Urban Style Backpack",
    "image": "img/潮流背包3.jpg",
    "category": "stylish-backpacks",
    "tag": "Unisex",
    "stockBadge": "Limited",
    "sizes": "One Size",
    "colors": "3 Colors",
    "season": "All Season",
    "desc": "Urban street style backpack with sleek design. Water-resistant fabric for all weather conditions.",
    "moq": "150 pcs"
  },
  {
    "name": "Designer Brand Bags",
    "image": "img/品牌包1.jpg",
    "category": "branded-bags",
    "tag": "Women's",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "4 Colors",
    "season": "All Season",
    "desc": "Premium branded fashion bags with elegant design. High-quality materials and craftsmanship.",
    "moq": "80 pcs"
  },
  {
    "name": "Luxury Handbags",
    "image": "img/品牌包2.jpg",
    "category": "branded-bags",
    "tag": "Women's",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "3 Colors",
    "season": "All Season",
    "desc": "Luxury handbags with sophisticated design. Perfect for formal occasions and everyday luxury.",
    "moq": "60 pcs"
  },
  {
    "name": "Premium Shoulder Bags",
    "image": "img/品牌包3.jpg",
    "category": "branded-bags",
    "tag": "Women's",
    "stockBadge": "Limited",
    "sizes": "One Size",
    "colors": "5 Colors",
    "season": "All Season",
    "desc": "Premium quality shoulder bags with stylish design. Durable hardware and premium leather.",
    "moq": "70 pcs"
  },
  {
    "name": "Girls' Cute Handbag Set",
    "image": "img/儿童手袋套装1.jpg",
    "category": "handbag-sets",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "6 Colors",
    "season": "All Season",
    "desc": "Adorable handbag set for little girls with matching accessories. Cute and colorful designs.",
    "moq": "200 pcs"
  },
  {
    "name": "Kids' Purse Set",
    "image": "img/儿童手袋套装2.jpg",
    "category": "handbag-sets",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "5 Colors",
    "season": "All Season",
    "desc": "Pretty purse set with mini bags and coin purses. Perfect for dress-up and pretend play.",
    "moq": "220 pcs"
  },
  {
    "name": "Little Girls' Bag Collection",
    "image": "img/儿童手袋套装3.jpg",
    "category": "handbag-sets",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "One Size",
    "colors": "7 Colors",
    "season": "All Season",
    "desc": "Collection of cute bags for little girls. Includes shoulder bag, crossbody, and mini backpack.",
    "moq": "250 pcs"
  },
  {
    "name": "Soft Kids' Slippers",
    "image": "img/儿童拖鞋1.jpg",
    "category": "kids-slippers",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "22-36",
    "colors": "6 Colors",
    "season": "All Season",
    "desc": "Ultra-soft plush slippers for kids with anti-slip sole. Warm and comfortable for indoor wear.",
    "moq": "300 pcs"
  },
  {
    "name": "Cartoon House Slippers",
    "image": "img/儿童拖鞋2.jpg",
    "category": "kids-slippers",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "20-34",
    "colors": "5 Colors",
    "season": "All Season",
    "desc": "Cute cartoon-themed slippers with soft lining. Perfect for home and casual indoor use.",
    "moq": "280 pcs"
  },
  {
    "name": "Comfort Kids' Slippers",
    "image": "img/儿童拖鞋3.jpg",
    "category": "kids-slippers",
    "tag": "Kids'",
    "stockBadge": "In Stock",
    "sizes": "22-38",
    "colors": "4 Colors",
    "season": "All Season",
    "desc": "Comfortable home slippers with memory foam insole. Supportive and warm for all-day wear.",
    "moq": "260 pcs"
  },
  {
    "name": "Premium Cotton Fabric Roll",
    "image": "img/纯棉布料1.jpg",
    "category": "cotton-fabric",
    "tag": "Fabric",
    "stockBadge": "In Stock",
    "sizes": "150cm Width",
    "colors": "12 Colors",
    "season": "All Season",
    "desc": "High-quality 100% cotton fabric roll. Soft, breathable, and perfect for garment production. Available in multiple colors.",
    "moq": "50 meters"
  },
  {
    "name": "Plain Cotton Textile",
    "image": "img/纯棉布料2.jpg",
    "category": "cotton-fabric",
    "tag": "Fabric",
    "stockBadge": "In Stock",
    "sizes": "145cm Width",
    "colors": "10 Colors",
    "season": "All Season",
    "desc": "Plain cotton textile with smooth texture. Ideal for shirts, dresses, and various apparel items.",
    "moq": "30 meters"
  },
  {
    "name": "Soft Cotton Material",
    "image": "img/纯棉布料3.jpg",
    "category": "cotton-fabric",
    "tag": "Fabric",
    "stockBadge": "Limited",
    "sizes": "160cm Width",
    "colors": "8 Colors",
    "season": "All Season",
    "desc": "Premium soft cotton material with excellent draping quality. Perfect for high-end clothing production.",
    "moq": "40 meters"
  },
  {
    "name": "Floral Print Summer Dress",
    "image": "img/花布连衣裙1.jpg",
    "category": "girls-printed",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "4-12Y",
    "colors": "6 Colors",
    "season": "Summer",
    "desc": "Beautiful floral print summer dress with lightweight fabric. Perfect for sunny days and beach vacations.",
    "moq": "220 pcs"
  },
  {
    "name": "Garden Print Dress",
    "image": "img/花布连衣裙2.jpg",
    "category": "girls-printed",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "3-10Y",
    "colors": "5 Colors",
    "season": "Summer",
    "desc": "Charming garden print dress with ruffled details. Sweet and stylish for young girls.",
    "moq": "200 pcs"
  },
  {
    "name": "Spring Floral Dress",
    "image": "img/花布连衣裙3.jpg",
    "category": "girls-printed",
    "tag": "Girls'",
    "stockBadge": "In Stock",
    "sizes": "5-14Y",
    "colors": "4 Colors",
    "season": "Spring",
    "desc": "Lovely spring floral dress with comfortable fit. Ideal for outdoor activities and family outings.",
    "moq": "180 pcs"
  }
];
